// <auto-generated />
namespace Shopping.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class infoOfCart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(infoOfCart));
        
        string IMigrationMetadata.Id
        {
            get { return "202102022218070_infoOfCart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
